common-abilities-debug-possess = Заклинаюча Стріла
    .desc = Стріляє отруйною стрілою. Дає тобі контроль над ціллю.
common-abilities-hammer-leap = Погром
    .desc = Атака по області. Стрибок спрямований за курсором.
common-abilities-bow-shotgun = Стріловик
    .desc = Постріл купою стріл за раз.
common-abilities-staff-fireshockwave = Кільце Вогню
    .desc = Підпалює землю вогненною ударною хвилєю.
common-abilities-sceptre-wardingaura = Захисна Аура
    .desc = Укріплює тебе і твоїх спільників силами природи на деякий час.

#Sword abilities
veloren-core-pseudo_abilities-sword-heavy_stance = Важка Стійка
    .desc = Атаки в цій стійці можуть похитнути ворогів та завдати більше пошкоджень ворогам, що похитнулися, але вони повільніші.
veloren-core-pseudo_abilities-sword-agile_stance = Спритна Стійка
    .desc = Атаки в цій стійці швидші, але слабші
veloren-core-pseudo_abilities-sword-defensive_stance = Захисна Стійка
    .desc = Атаки в цій стійці можуть виконувати роль слабкого блокування або парирування
veloren-core-pseudo_abilities-sword-crippling_stance = Руйнівна Стійка
    .desc = Атаки в цій стійці створюють або погіршують тривалі пошкодження
veloren-core-pseudo_abilities-sword-cleaving_stance = Розсікаюча Стійка
    .desc = Атаки в цій стійці можут вразити кількох ворогів
veloren-core-pseudo_abilities-sword-double_slash = Подвійний Розріз
    .desc = Комбо з двох ударів
common-abilities-sword-basic_double_slash =	Основний Подвійний Розріз
    .desc = Основне комбо з двох ударів
common-abilities-sword-heavy_double_slash = Важкий Подвійний Розріз
    .desc = Повільніше комбо з двох ударів, яке може похитнути ворога
common-abilities-sword-agile_double_slash = Спритний Подвійний Розріз
    .desc = Швидке комбо з двох ударів із легкими ударами
common-abilities-sword-defensive_double_slash = Захист: Подвійний Розріз
    .desc = Швидке комбо з двох ударів, що зменшує вплив ворожих ударів
common-abilities-sword-crippling_double_slash = Руйнівний Подвійний Розріз
    .desc = Комбо з двох ударів, яке може подовжити кровотечу ворога
common-abilities-sword-cleaving_double_slash = Розсікаючий Подвійний Розріз
    .desc = Комбо з двох ударів, яке може пробити кількох ворогів
veloren-core-pseudo_abilities-sword-secondary_ability = Додаткова Здатність Меча
    .desc = Здатність прив’язана до додаткової атаки
common-abilities-sword-basic_thrust = Основний Випад
    .desc = Зарядка випаду зробить його сильнішим 
common-abilities-sword-heavy_slam = Важкий Удар
    .desc = Потужний мах над головою, який можна зарядити, щоб похитнути ворога сильніше  
common-abilities-sword-agile_perforate = Перфорування
    .desc =	Стрімкий шквал легких атак
common-abilities-sword-agile_dual_perforate = Перфорування
    .desc = Стрімкий шквал легких атак двома мечами
common-abilities-sword-defensive_vital_jab = Захист: Вирішальний Удар
    .desc = Швидко-заряджений удар, який завдає більше шкоди парированим ворогам
common-abilities-sword-crippling_deep_rend = Глубокий Поріз
    .desc = Удар, спрямований на вже відкриту рану, завдає більше шкоди ворогам з кровотечею 
common-abilities-sword-cleaving_spiral_slash = Спіральний Розріз
    .desc = Махніть своїм лезом повністю навколо себе, щоб вразити будь-кого поруч
common-abilities-sword-cleaving_dual_spiral_slash =	Спіральний Розріз
    .desc = Махніть обома лезами повністю навколо себе, щоб вразити будь-кого поруч
veloren-core-pseudo_abilities-sword-crescent_slash = Півмісячний Розріз
    .desc =
        Діагональний розріз вгору
        Модифікується залежно від вашої стійки
common-abilities-sword-basic_crescent_slash = Основний Півмісячний Розріз
    .desc = Основний діагональний розріз вгору
common-abilities-sword-heavy_crescent_slash = Важкий Півмісячний Розріз
    .desc = Важкий діагональний розріз вгору, який може похитнути ворога
common-abilities-sword-agile_crescent_slash = Спритний Півмісячний Розріз
    .desc = Легкий діагональний розріз вгору
common-abilities-sword-defensive_crescent_slash = Захист: Півмісячний Розріз
    .desc = Паріруючий діагональний розріз вгору
common-abilities-sword-crippling_crescent_slash = Руйнівний Півмісячний Розріз
    .desc = Діагональний розріз вгору, який може викликати кровотечу
common-abilities-sword-cleaving_crescent_slash = Розсікаючий Півмісячний Розріз	
    .desc = Діагональний розріз вгору, який може пробити ворогів
veloren-core-pseudo_abilities-sword-fell_strike = Лютий Удар
    .desc = 
        Швидкий і сильний розріз
        Модифікується залежно від вашої стійки
common-abilities-sword-basic_fell_strike = Основний Лютий Удар
    .desc = Основний швидкий і сильний розріз
common-abilities-sword-heavy_fell_strike =	Важкий Лютий Удар
    .desc = Сильний розріз, який може похитнути ворога
common-abilities-sword-agile_fell_strike = Спритний Лютий Удар
    .desc = Дуже швидкий і сильний розріз
common-abilities-sword-defensive_fell_strike = Захист: Лютий Удар
    .desc = Паріруючий швидкий і сильний розріз
common-abilities-sword-crippling_fell_strike = 
    .desc = Швидкий і сильний розріз, який може викликати кровотечу
common-abilities-sword-cleaving_fell_strike =	
    .desc = Швидкий і сильний розріз, який може пробити ворогів
veloren-core-pseudo_abilities-sword-skewer = Шпажка
    .desc = 
        Колючий випад
        Модифікується залежно від вашої стійки
common-abilities-sword-basic_skewer = Базова Шпажка
    .desc = Основний колючий випад
common-abilities-sword-heavy_skewer = Важка Шпажка
    .desc = Колючий випад, який може похитнути ворога
common-abilities-sword-agile_skewer = Спритна Шпажка
    .desc = Швидкий колючий випад
common-abilities-sword-defensive_skewer = Захист: Шпажка
    .desc = Паріруючий колючий випад 
common-abilities-sword-crippling_skewer = Руйнівна Шпажка
    .desc = Колючий випад, який може викликати кровотечу
common-abilities-sword-cleaving_skewer = Розсікаюча Шпажка
    .desc = Колючий випад, який может пробити ворогів